[package]
name = "building-blocks-editor"
version = "0.1.0"
authors = ["Duncan <bonsairobo@gmail.com>"]
edition = "2018"

[profile.dev]
opt-level = 2

[profile.release]
lto = true

[dependencies]
approx = "0.4"
fnv = "1.0"
glam = { version = "0.10", features = ["mint"] }
mint = "0.5"
serde = "1.0"
thread_local = "1.0"

[dependencies.bevy]
# version = "0.3"
# path = "../bevy"
git = "https://github.com/bevyengine/bevy"
branch = "master"

[dependencies.building-blocks]
git = "https://github.com/bonsairobo/building-blocks"
branch = "main"
# version = "0.2.1"
features = ["mesh", "glam", "nalgebra", "ncollide"]

[dependencies.bevy-building-blocks]
git = "https://github.com/bonsairobo/bevy-building-blocks"
branch = "main"
# path = "../bevy-building-blocks"

[features]
default = []
